import shutil
from pathlib import Path
from typing import Tuple
from app.integrations.ffmpeg import convert_audio
from app.services.errors import ExportError
from app.storage.paths import (
    get_job_demucs_dir,
    get_job_instrumental_path,
    get_job_vocals_path
)

def discover_demucs_outputs(job_id: str, model_name: str) -> Tuple[Path, Path]:
    """
    Locates the vocals.wav and no_vocals.wav files generated by Demucs in the workspace.
    Returns:
        Tuple[Path, Path]: (instrumental_wav_path, vocals_wav_path)
    """
    demucs_dir = get_job_demucs_dir(job_id)
    # The expected track directory name is the stem of the normalized input file: 'source_normalized'
    track_dir = demucs_dir / model_name / "source_normalized"
    
    no_vocals = track_dir / "no_vocals.wav"
    vocals = track_dir / "vocals.wav"
    
    # Fallback to search recursively if the exact path structure is not matched
    if not no_vocals.exists() or not vocals.exists():
        no_vocals_matches = list(demucs_dir.glob("**/no_vocals.wav"))
        vocals_matches = list(demucs_dir.glob("**/vocals.wav"))
        if no_vocals_matches:
            no_vocals = no_vocals_matches[0]
        if vocals_matches:
            vocals = vocals_matches[0]
            
    if not no_vocals.exists():
        raise ExportError(f"Could not locate Demucs instrumental (no_vocals.wav) output under {demucs_dir}")
        
    return no_vocals, vocals

def export_separation_outputs(job_id: str, model_name: str, output_format: str = "wav") -> Tuple[Path, Path]:
    """
    Discovers Demucs WAV outputs and exports them to the final job directory,
    converting to the requested output format if necessary.
    Returns:
        Tuple[Path, Path]: (final_instrumental_path, final_vocals_path)
    """
    try:
        no_vocals_wav, vocals_wav = discover_demucs_outputs(job_id, model_name)
        
        dest_inst = get_job_instrumental_path(job_id, output_format)
        dest_voc = get_job_vocals_path(job_id, output_format)
        
        # If output format is WAV, copy it directly. Otherwise, use ffmpeg to convert.
        if output_format.lower() == "wav":
            shutil.copy2(no_vocals_wav, dest_inst)
            if vocals_wav.exists():
                shutil.copy2(vocals_wav, dest_voc)
        else:
            convert_audio(no_vocals_wav, dest_inst)
            if vocals_wav.exists():
                convert_audio(vocals_wav, dest_voc)
                
        return dest_inst, dest_voc
        
    except Exception as e:
        if isinstance(e, ExportError):
            raise e
        raise ExportError(f"Failed to export separation outputs: {str(e)}", original_error=e)
